Attempt to use OpenMDAO pixi environment in dymos testing. (#1220)
* Attempt to use OpenMDAO pixi environment in dymos testing.

* working on getting correct version.

* cancel running jobs if re-pushed same branch.

* progress.  also, kill doc jobs if branch is re-pushed.

* pin jupyter-book < 2

* Allow oversubscription for MPI in tests.

* continue on error

* correctly set shell-hook for setting up MPI

* Now build docs with the OpenMDAO pixi files.

* fix doc build

* use openmdao dev environment for docs.

* fix logic for coveralls upload

* use openmdao_setup_pixi action from openmdao master

* use setup_openmdao_pixi from OpenMDAO@master for now

diff --git a/.github/workflows/dymos_tests_workflow.yml b/.github/workflows/dymos_tests_workflow.yml
--- a/.github/workflows/dymos_tests_workflow.yml
+++ b/.github/workflows/dymos_tests_workflow.yml
@@ -75,6 +75,11 @@ on:
         required: false
         default: false
 
+concurrency:
+  # Cancel any existing CI runs if we push to this branch
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 run-name:  ${{ inputs.run_name }}
 
 jobs:
@@ -94,95 +99,48 @@ jobs:
         include:
           # baseline versions
           - NAME: baseline
-            PY: '3.13'
-            NUMPY: '2.2'
-            SCIPY: '1.15'
-            PETSc: '3.23'
-            PYOPTSPARSE: 'v2.13.1'
-            SNOPT: '7.7'
-            OPENMDAO: 'latest'
-            PEP517: true
-            OPTIONAL: '[all]'
-            JAX: true
-            EXCLUDE: ${{ github.event_name == 'workflow_dispatch'  && ! inputs.baseline }}
-
-          # baseline versions except no pyoptsparse or SNOPT
-          - NAME: no_pyoptsparse
-            PY: '3.13'
-            NUMPY: '2.2'
-            SCIPY: '1.15'
-            PETSc: '3.23'
-            OPENMDAO: 'latest'
-            OPTIONAL: '[test]'
-            EXCLUDE: ${{ github.event_name == 'workflow_dispatch'  && ! inputs.no_pyoptsparse }}
-
-          # baseline versions except with pyoptsparse but no SNOPT
-          - NAME: no_snopt
-            PY: '3.13'
-            NUMPY: '2.2'
-            SCIPY: '1.15'
-            PETSc: '3.23'
-            PYOPTSPARSE: 'v2.13.1'
-            OPENMDAO: 'latest'
-            OPTIONAL: '[all]'
-            JAX: true
-            EXCLUDE: ${{ github.event_name == 'workflow_dispatch'  && ! inputs.no_snopt }}
+            OPENMDAO_PIXI_ENVIRONMENT: 'py313'
+            OPENMDAO_INSTALL_FROM: 'pypi'
+            OPENMDAO: '3.41.0'
+            DYMOS_2: False
+            PEP517: True
+            EXCLUDE: ${{ github.event_name == 'workflow_dispatch'  && ! inputs.latest }}
 
           # baseline versions except no MPI/PETSc
           - NAME: no_mpi
-            PY: '3.13'
-            NUMPY: '2.2'
-            SCIPY: '1.15'
-            PYOPTSPARSE: 'v2.13.1'
-            OPENMDAO: 'latest'
-            OPTIONAL: '[test]'
-            EXCLUDE: ${{ github.event_name == 'workflow_dispatch'  && ! inputs.no_mpi }}
+            OPENMDAO_PIXI_ENVIRONMENT: 'default'
+            OPENMDAO_INSTALL_FROM: 'pypi'
+            OPENMDAO: '3.41.0'
+            DYMOS_2 : False
+            EXCLUDE: ${{ github.event_name == 'workflow_dispatch'  && ! inputs.latest }}
 
           # latest versions
           - NAME: latest
-            PY: '3'
-            NUMPY: '2'
-            SCIPY: '1'
-            PETSc: '3.23.5'
-            PYOPTSPARSE: 'latest'
-            SNOPT: '7.7'
-            OPENMDAO: 'dev'
-            OPTIONAL: '[all]'
-            JAX: true
+            OPENMDAO_PIXI_ENVIRONMENT: 'py313'
+            OPENMDAO_INSTALL_FROM: 'github'
+            OPENMDAO: ''
+            DYMOS_2 : False
             EXCLUDE: ${{ github.event_name == 'workflow_dispatch'  && ! inputs.latest }}
 
           # latest versions dymos 2 testing
           - NAME: latest_dymos_2
-            PY: '3'
-            NUMPY: '2'
-            SCIPY: '1'
-            PETSc: '3.23.5'
-            PYOPTSPARSE: 'latest'
-            SNOPT: '7.7'
-            OPENMDAO: 'dev'
-            OPTIONAL: '[all]'
-            JAX: true
+            OPENMDAO_PIXI_ENVIRONMENT: 'py313'
+            OPENMDAO_INSTALL_FROM: 'github'
+            OPENMDAO: ''
             DYMOS_2 : True
             EXCLUDE: ${{ github.event_name == 'workflow_dispatch'  && ! inputs.latest }}
 
           # oldest supported versions
           - NAME: oldest
-            PY: '3.9'
-            NUMPY: '1.25'
-            SCIPY: '1.11'
-            OPENMPI: '4.0'
-            MPI4PY: '3.0'
-            PETSc: '3.13'
-            PYOPTSPARSE: 'v2.10.2'
-            SNOPT: '7.2'
-            OPENMDAO: 3.36.0
-            MATPLOTLIB: '3.5'
-            OPTIONAL: '[test]'
+            OPENMDAO_PIXI_ENVIRONMENT: 'oldest'
+            OPENMDAO_INSTALL_FROM: 'pypi'
+            OPENMDAO: '3.36.0'
             EXCLUDE: ${{ github.event_name == 'workflow_dispatch'  && ! inputs.oldest }}
 
     steps:
       - name: Display run details
         run: |
+          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
           echo "============================================================="
           echo "Run #${GITHUB_RUN_NUMBER}"
           echo "Run ID: ${GITHUB_RUN_ID}"
@@ -198,142 +156,22 @@ jobs:
             fi
           fi
 
-      - name: Create SSH key
-        if: ${{ ! matrix.EXCLUDE }}
-        env:
-          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
-          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
-        run: |
-          mkdir -p ~/.ssh/
-          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
-          sudo chmod 600 ~/.ssh/id_rsa
-          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
-
       - name: Checkout code
         if: ${{ ! matrix.EXCLUDE }}
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
 
-      - name: Setup conda
-        if: ${{ ! matrix.EXCLUDE }}
-        uses: conda-incubator/setup-miniconda@v3
+      - name: 'Setup OpenMDAO pixi Environment'
+        id: setup_pixi_environment
+        uses: OpenMDAO/OpenMDAO/.github/actions/setup_openmdao_pixi@master
         with:
-          python-version: ${{ matrix.PY }}
-          miniconda-version: "latest"
-          channels: conda-forge
-          conda-remove-defaults: true
-
-      - name: Install Numpy/Scipy
-        if: ${{ ! matrix.EXCLUDE }}
-        run: |
-          echo "============================================================="
-          echo "Install Numpy/Scipy"
-          echo "============================================================="
-          conda install numpy=${{ matrix.NUMPY }} scipy=${{ matrix.SCIPY }} -q -y
-
-      - name: Install jax
-        if: ${{ ! matrix.EXCLUDE && matrix.JAX }}
-        run: |
-          echo "============================================================="
-          echo "Install jax"
-          echo "============================================================="
-          python -m pip install jax
-
-      - name: Install PETSc
-        if: ${{ ! matrix.EXCLUDE && matrix.PETSc }}
-        run: |
-          echo "============================================================="
-          echo "Install PETSc"
-          echo "============================================================="
-          if [[ "${{ matrix.OPENMPI }}" && "${{ matrix.MPI4PY }}" ]]; then
-            conda install openmpi=${{ matrix.OPENMPI }} mpi4py=${{ matrix.MPI4PY }} petsc4py=${{ matrix.PETSc }} -q -y
-          elif [[ "${{ matrix.MPI4PY }}" ]]; then
-            conda install mpich mpi4py=${{ matrix.MPI4PY }} petsc4py=${{ matrix.PETSc }} -q -y
-          else
-            conda install mpich mpi4py petsc4py=${{ matrix.PETSc }} -q -y
-          fi
-          export OMPI_MCA_rmaps_base_oversubscribe=1
-          export OMPI_MCA_btl=^openib
-          echo "OMPI_MCA_rmaps_base_oversubscribe=1" >> $GITHUB_ENV
-          echo "OMPI_MCA_btl=^openib" >> $GITHUB_ENV
-          echo "-----------------------"
-          echo "Quick test of mpi4py:"
-          mpirun -n 2 python -c "from mpi4py import MPI; print(f'Rank: {MPI.COMM_WORLD.rank}')"
-          echo "-----------------------"
-          echo "Quick test of petsc4py:"
-          mpirun -n 2 python -c "import numpy; from mpi4py import MPI; comm = MPI.COMM_WORLD; import petsc4py; petsc4py.init(); x = petsc4py.PETSc.Vec().createWithArray(numpy.ones(5)*comm.rank, comm=comm);  print(x.getArray())"
-          echo "-----------------------"
-
-      - name: Install pyOptSparse
-        id: build_pyoptsparse
-        if: ${{ ! matrix.EXCLUDE && matrix.PYOPTSPARSE }}
-        run: |
-          echo "============================================================="
-          echo "Install pyoptsparse"
-          echo "============================================================="
-
-          if [[ "${{ matrix.PYOPTSPARSE }}" == "conda-forge" ]]; then
-            if [[ "${{ matrix.SNOPT }}" ]]; then
-              echo "SNOPT ${{ matrix.SNOPT }} was requested but is not available on conda-forge"
-            fi
-
-            conda install -c conda-forge pyoptsparse
-          else
-            pip install git+https://github.com/OpenMDAO/build_pyoptsparse
-
-            if [[ "${{ matrix.PYOPTSPARSE }}" == "latest" ]]; then
-              LATEST_URL=`curl -fsSLI -o /dev/null -w %{url_effective} https://github.com/mdolab/pyoptsparse/releases/latest`
-              LATEST_VER=`echo $LATEST_URL | awk '{split($0,a,"/tag/"); print a[2]}'`
-              BRANCH="-b $LATEST_VER"
-            else
-              BRANCH="-b ${{ matrix.PYOPTSPARSE }}"
-            fi
-
-            if [[ "${{ matrix.PAROPT }}" ]]; then
-              PAROPT="-a"
-            fi
-
-            if [[ "${{ matrix.SNOPT }}" == "7.7" && "${{ secrets.SNOPT_LOCATION_77 }}" ]]; then
-              echo "  > Secure copying SNOPT 7.7 over SSH"
-              mkdir SNOPT
-              scp -qr ${{ secrets.SNOPT_LOCATION_77 }} SNOPT
-              SNOPT="-s SNOPT/src"
-            elif [[ "${{ matrix.SNOPT }}" == "7.2" && "${{ secrets.SNOPT_LOCATION_72 }}" ]]; then
-              echo "  > Secure copying SNOPT 7.2 over SSH"
-              mkdir SNOPT
-              scp -qr ${{ secrets.SNOPT_LOCATION_72 }} SNOPT
-              SNOPT="-s SNOPT/source"
-            elif [[ "${{ matrix.SNOPT }}" ]]; then
-              echo "SNOPT version ${{ matrix.SNOPT }} was requested but source is not available"
-            fi
-
-            build_pyoptsparse $BRANCH $PAROPT $SNOPT
-          fi
-
-      - name: Install OpenMDAO
-        if: ${{ ! matrix.EXCLUDE && matrix.OPENMDAO }}
-        run: |
-          echo "============================================================="
-          echo "Install OpenMDAO"
-          echo "============================================================="
-          if [[ "${{ matrix.OPENMDAO }}" == "dev" ]]; then
-            pip install git+https://github.com/OpenMDAO/OpenMDAO
-          elif [[ "${{ matrix.OPENMDAO }}" == "latest" ]]; then
-            echo "The latest version OpenMDAO will be installed from pypi per the Dymos dependency"
-          else
-            pip install openmdao==${{ matrix.OPENMDAO }}
-          fi
-
-      - name: Install Matplotlib
-        if: ${{ ! matrix.EXCLUDE && matrix.MATPLOTLIB }}
-        run: |
-          echo "============================================================="
-          echo "Install requested version of Matpltlib"
-          echo "============================================================="
-          python -m pip install matplotlib==${{ matrix.MATPLOTLIB }}
+          environment: '${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }}'
+          openmdao_install_from: '${{ matrix.OPENMDAO_INSTALL_FROM }}'
+          openmdao_version: '${{ matrix.OPENMDAO }}'
 
       - name: Install Dymos
         if: ${{ ! matrix.EXCLUDE }}
         run: |
+          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
           echo "============================================================="
           echo "Install Dymos"
           echo "============================================================="
@@ -341,21 +179,22 @@ jobs:
             echo "-----------------------------------------------------------"
             echo "Installing from PyPI"
             echo "-----------------------------------------------------------"
-            python -m pip install dymos${{ matrix.OPTIONAL }}
+            python -m pip install dymos --no-deps
           elif [[ "${{ matrix.PEP517 }}" == "true" ]]; then
             pip wheel --no-deps --use-pep517 .
-            WHEEL=`find dymos-*.whl`
+            WHEEL=$(find dymos-*.whl)
             echo "-----------------------------------------------------------"
             echo "Installing from wheel: $WHEEL"
             echo "-----------------------------------------------------------"
-            python -m pip install $WHEEL${{ matrix.OPTIONAL }}
+            python -m pip install "$WHEEL"
           else
-            python -m pip install .${{ matrix.OPTIONAL }}
+            python -m pip install .  --no-deps
           fi
 
       - name: Install optional dependencies
-        if: ${{ ! matrix.EXCLUDE && matrix.OPTIONAL == '[all]' }}
+        if: matrix.OPENMDAO_PIXI_ENVIRONMENT == 'dev'
         run: |
+          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
           echo "============================================================="
           echo "Install additional packages for testing/coverage"
           echo "============================================================="
@@ -364,67 +203,66 @@ jobs:
           playwright install --with-deps
 
       - name: Set Environment for Dymos 2
-        if: ${{ matrix.DYMOS_2 }}
+        if: matrix.DYMOS_2
         shell: bash -l {0}
         run: |
+          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
           echo "============================================================="
           echo "Setting environement variable DYMOS_2=1"
           echo "============================================================="
-          export DYMOS_2=1
-          echo "DYMOS_2=1" >> $GITHUB_ENV
-
-      - name: Display environment info
-        id: env_info
-        if: ${{ ! matrix.EXCLUDE }}
-        run: |
-          printenv
-
-          conda info
-          conda list
-          conda env export --name test --file environment.yml
-          mv environment.yml ${{ matrix.NAME }}_environment.yml
-
-          echo "============================================================="
-          echo "Check installed versions of Python, Numpy and Scipy"
-          echo "============================================================="
-          python -c "ver='${{ matrix.PY }}'; import sys; assert str(sys.version).startswith(ver), \
-                    f'Python version {sys.version} is not the requested version ({ver})'"
-
-          python -c "ver='${{ matrix.NUMPY }}'; import numpy; assert str(numpy.__version__).startswith(ver), \
-                    f'Numpy version {numpy.__version__} is not the requested version ({ver})'"
-
-          python -c "ver='${{ matrix.SCIPY }}'; import scipy; assert str(scipy.__version__).startswith(ver), \
-                    f'Scipy version {scipy.__version__} is not the requested version ({ver})'"
-
-      - name: Display dependency tree
-        if: failure() && steps.env_info.outcome == 'failure'
-        run: |
-          pip install pipdeptree
-          pipdeptree
-
-      - name: Upload environment artifact
-        if: ${{ ! matrix.EXCLUDE }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ matrix.NAME }}_environment
-          path: ${{ matrix.NAME }}_environment.yml
-          retention-days: 5
+          export "$DYMOS_2"=1
+          echo "$DYMOS_2=1" >> $"GITHUB_ENV"
 
       - name: Perform linting with Ruff
         if: ${{ ! matrix.EXCLUDE && matrix.NAME == 'baseline' }}
         run: |
+          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
           echo "============================================================="
           echo "Lint Dymos code per settings in pyproject.toml"
           echo "============================================================="
-          python -m pip install ruff
           ruff check . --config pyproject.toml
 
+      - name: Check MPI and PETSc
+        continue-on-error: true
+        run: |
+          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
+          if python -c "import mpi4py, petsc4py" 2>/dev/null; then
+            echo "============================================================="
+            echo "Check MPI and PETSc installation"
+            echo "============================================================="
+            export PRTE_MCA_rmaps_default_mapping_policy=:oversubscribe
+            export OMPI_MCA_rmaps_base_oversubscribe=1
+            export OMPI_MCA_btl=^openib
+            echo "-----------------------"
+            echo "Quick test of mpi4py:"
+            mpirun -n 3 python -c "from mpi4py import MPI; print(f'Rank: {MPI.COMM_WORLD.rank}')"
+            echo "-----------------------"
+            echo "Quick test of petsc4py:"
+            mpirun -n 3 python -c "import numpy; from mpi4py import MPI; comm = MPI.COMM_WORLD; \
+              import petsc4py; petsc4py.init(); \
+              x = petsc4py.PETSc.Vec().createWithArray(numpy.ones(5)*comm.rank, comm=comm);  \
+              print(x.getArray())"
+            echo "-----------------------"
+
+            # shellcheck disable=SC2129
+            echo "PRTE_MCA_rmaps_default_mapping_policy=:oversubscribe" >> "$GITHUB_ENV"
+            echo "OMPI_MCA_rmaps_base_oversubscribe=1" >> "$GITHUB_ENV"
+            echo "OMPI_MCA_btl=^openib" >> "$GITHUB_ENV"
+
+            echo "Workaround for intermittent failures with OMPI https://github.com/open-mpi/ompi/issues/7393"
+            echo "TMPDIR=/tmp" >> "$GITHUB_ENV"
+          else
+            echo "mpi4py or petsc4py not installed in this environment, skipping MPI checks"
+          fi
+
       - name: Run tests
+        id: run_tests
         if: ${{ ! matrix.EXCLUDE }}
         env:
           DYMOS_CHECK_PARTIALS: True
+        continue-on-error: true
         run: |
-          HAS_ERRORS=false
+          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
           echo "============================================================="
           echo "Run Tests"
           echo "Environment:"
@@ -435,7 +273,7 @@ jobs:
           testflo -b benchmark --pre_announce || HAS_ERRORS=true
           # Run the readme test from the checked out directory.
           testflo -n 1 ./dymos/test/test_readme.py --pre_announce || HAS_ERRORS=true
-          cd $HOME
+          cd "$HOME"
           if [[ "${{ matrix.NAME }}" != "latest" ]]; then
             testflo dymos -n 4 --pre_announce --show_skipped --durations 20 --coverage --coverpkg dymos || HAS_ERRORS=true
           else
@@ -448,20 +286,27 @@ jobs:
           fi
 
       - name: Submit coverage
-        if: github.event_name != 'workflow_dispatch'
+        if: steps.run_tests.outcome == 'success' && github.event_name != 'workflow_dispatch'
         continue-on-error: true
         env:
           COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           COVERALLS_SERVICE_NAME: "github"
           COVERALLS_PARALLEL: True
         run: |
+          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
           echo "============================================================="
           echo "Submit coverage"
           echo "============================================================="
-          cp $HOME/.coverage .
+          cp "$HOME"/.coverage .
           pip install coveralls
-          SITE_DIR=`python -c 'import site; print(site.getsitepackages()[-1])'`
-          coveralls --basedir $SITE_DIR
+          SITE_DIR=$(python -c 'import site; print(site.getsitepackages()[-1])')
+          coveralls --basedir "$SITE_DIR"
+
+      - name: Fail the workflow if tests failed
+        if: steps.run_tests.outcome != 'success'
+        run: |
+          echo "Tests failed"
+          exit 1
 
   coveralls:
     name: Finish coveralls
