fail if any tests encounter errors but run them all

diff --git a/.github/workflows/dymos_tests_workflow.yml b/.github/workflows/dymos_tests_workflow.yml
--- a/.github/workflows/dymos_tests_workflow.yml
+++ b/.github/workflows/dymos_tests_workflow.yml
@@ -422,21 +422,27 @@ jobs:
         env:
           DYMOS_CHECK_PARTIALS: True
         run: |
+          HAS_ERRORS=false
           echo "============================================================="
           echo "Run Tests"
           echo "Environment:"
           echo "   DYMOS_CHECK_PARTIALS: $DYMOS_CHECK_PARTIALS"
           echo "============================================================="
-          testflo -n 1 docs/dymos_book/test --pre_announce || echo "One or more tests failed."
-          testflo -n 1 joss/test --pre_announce || echo "One or more tests failed."
-          testflo -b benchmark --pre_announce || echo "One or more tests failed."
+          testflo -n 1 docs/dymos_book/test --pre_announce || HAS_ERRORS=true
+          testflo -n 1 joss/test --pre_announce || HAS_ERRORS=true
+          testflo -b benchmark --pre_announce || HAS_ERRORS=true
           # Run the readme test from the checked out directory.
-          testflo -n 1 ./dymos/test/test_readme.py --pre_announce || echo "One or more tests failed."
+          testflo -n 1 ./dymos/test/test_readme.py --pre_announce || HAS_ERRORS=true
           cd $HOME
           if [[ "${{ matrix.NAME }}" != "latest" ]]; then
-            testflo dymos -n 4 --pre_announce --show_skipped --durations 20 --coverage --coverpkg dymos || echo "One or more tests failed."
+            testflo dymos -n 4 --pre_announce --show_skipped --durations 20 --coverage --coverpkg dymos || HAS_ERRORS=true
           else
-            testflo dymos -n 4 --pre_announce --show_skipped --durations 20 || echo "One or more tests failed."
+            testflo dymos -n 4 --pre_announce --show_skipped --durations 20 || HAS_ERRORS=true
+          fi
+
+          if [ "$HAS_ERRORS" = true ]; then
+            echo "One or more commands failed"
+            exit 1
           fi
 
       - name: Submit coverage
